import { chromium } from "playwright";
import PocketBase from "pocketbase";
const out = process.argv[2]; const B = "http://localhost:5199";
const admin = new PocketBase("http://127.0.0.1:8099");
await admin.collection("_superusers").authWithPassword("ci@test.local", "cipassword123");
await admin.send("/api/cosmic/admin/balance/snapshot", { method: "POST" });
await admin.send("/api/cosmic/admin/alliance-saga", { method: "POST" });
await admin.send("/api/cosmic/admin/market-maker", { method: "POST" });
// Historique de démonstration (14 jours) pour voir les courbes.
const rec = (await admin.collection("game_config").getFullList({ filter: 'key = "balance_history"' }))[0];
const last = rec.data.days.at(-1);
const days = Array.from({ length: 14 }, (_, i) => {
  const d = new Date(Date.now() - (13 - i) * 86400000).toISOString().slice(0, 10);
  return { ...last, day: d, pvpBattles: 6 + (i % 3), pvpAttackerWins: 4 + (i % 2), raidsWon: 20 + i * 2, raidsLost: 2 + Math.floor(i / 4), lairsTaken: i > 9 ? 1 : 0, avgHangarAttack: 0.7 + i * 0.02, medianProduction: 5000 + i * 300, topWarlord: last.topWarlord * (1 - i * 0.03) };
});
await admin.collection("game_config").update(rec.id, { data: { days } });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 1000 } });
const errors = []; page.on("pageerror", (e) => errors.push(e.message));
const dismiss = async () => { for (let i=0;i<5;i++){ const b=page.getByRole("button",{name:/Plus tard/i}); if(await b.count()){await b.first().click();await page.waitForTimeout(400);} else await page.keyboard.press("Escape"); } };
await page.goto(B);
await page.getByPlaceholder("Pseudo ou email").fill("baladmin@test.dev");
await page.getByPlaceholder("Mot de passe").fill("motdepasse1");
await page.getByRole("button", { name: /^Connexion$/i }).first().click();
await page.waitForURL("**/game**", { timeout: 20000 });
await page.goto(`${B}/game/admin?onglet=balance`); await page.waitForTimeout(3500); await dismiss();
await page.getByText("Historique quotidien").scrollIntoViewIfNeeded();
const chart = page.locator("svg[role=img]").first(); await chart.hover({ position: { x: 200, y: 60 } }); await page.waitForTimeout(300);
await page.screenshot({ path: `${out}/v55_history.png` });
await page.goto(`${B}/game/admin?onglet=players`); await page.waitForTimeout(2500); await dismiss();
await page.getByRole("button", { name: /Bravo|Renomme/ }).first().click(); await page.waitForTimeout(800);
await page.screenshot({ path: `${out}/v55_players.png` });
await page.goto(`${B}/game/marche`); await page.waitForTimeout(3000); await dismiss();
await page.screenshot({ path: `${out}/v55_market.png` });
await page.setViewportSize({ width: 390, height: 900 });
await page.goto(`${B}/game/admin?onglet=balance`); await page.waitForTimeout(3000); await dismiss();
const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
console.log("errors", errors, "overflow", overflow);
await browser.close();
